import image from "../assets/Rectangle 1.png";

const ExploreCards = [
  {
    id: 1,
    organization: "Slum2School Africa",
    title: "Education for Every Child",
    description:
      "This campaign focuses on giving underprivileged children access to quality education and learning materials.",
    goal: "₦5,000,000",
    raised: "₦2,000,000",
    progress: 40,
    daysLeft: 25,
    image: image,
  },
  {
    id: 2,
    organization: "Hope Foundation",
    title: "Clean Water for Rural Homes",
    description:
      "Providing clean and safe drinking water to families in underserved rural areas across Nigeria.",
    goal: "₦3,500,000",
    raised: "₦1,200,000",
    progress: 34,
    daysLeft: 18,
    image: image,
  },
  {
    id: 3,
    organization: "FeedTheFuture",
    title: "Zero Hunger Mission",
    description:
      "Supporting food drives and school feeding programs to reduce child hunger in rural communities.",
    goal: "₦4,000,000",
    raised: "₦2,800,000",
    progress: 70,
    daysLeft: 12,
    image: image,
  },
  {
    id: 4,
    organization: "HealthBridge Africa",
    title: "Maternal Care Support",
    description:
      "Providing safe delivery kits and healthcare access for expectant mothers in remote regions.",
    goal: "₦6,000,000",
    raised: "₦3,000,000",
    progress: 50,
    daysLeft: 22,
    image: image,
  },
  {
    id: 5,
    organization: "EcoLife Initiative",
    title: "Tree Planting for Climate Action",
    description:
      "Planting trees across deforested areas to combat climate change and restore biodiversity.",
    goal: "₦2,500,000",
    raised: "₦1,000,000",
    progress: 40,
    daysLeft: 30,
    image: image,
  },
  {
    id: 6,
    organization: "BrightMinds Africa",
    title: "Scholarship for Brilliant Students",
    description:
      "Empowering talented but financially disadvantaged students through scholarships and mentorship.",
    goal: "₦8,000,000",
    raised: "₦5,000,000",
    progress: 63,
    daysLeft: 19,
    image: image,
  },
  {
    id: 7,
    organization: "SafeHaven Shelter",
    title: "Rescue for Street Children",
    description:
      "Providing housing, care, and education for children living on the streets.",
    goal: "₦6,500,000",
    raised: "₦2,500,000",
    progress: 38,
    daysLeft: 15,
    image: image,
  },
  {
    id: 8,
    organization: "HealthFirst",
    title: "Free Medical Outreach",
    description:
      "Delivering free healthcare services, medications, and check-ups to low-income families.",
    goal: "₦4,500,000",
    raised: "₦2,100,000",
    progress: 47,
    daysLeft: 27,
    image: image,
  },
  {
    id: 9,
    organization: "AgriBoost Initiative",
    title: "Farming Equipment for Youth",
    description:
      "Supporting young farmers with tools, seeds, and training to enhance food security.",
    goal: "₦3,800,000",
    raised: "₦2,000,000",
    progress: 53,
    daysLeft: 21,
    image: image,
  },
  {
    id: 10,
    organization: "VisionAid",
    title: "Eye Care for All",
    description:
      "Providing free eye screening, glasses, and surgeries for people in rural communities.",
    goal: "₦2,200,000",
    raised: "₦900,000",
    progress: 41,
    daysLeft: 10,
    image: image,
  },
  {
    id: 11,
    organization: "YouthEmpower",
    title: "Skill Acquisition for Teenagers",
    description:
      "Training young people in digital skills, tailoring, and crafts to empower them economically.",
    goal: "₦4,000,000",
    raised: "₦1,500,000",
    progress: 38,
    daysLeft: 28,
    image: image,
  },
  {
    id: 12,
    organization: "Care4Seniors",
    title: "Elderly Home Support",
    description:
      "Providing shelter, meals, and companionship for the elderly living in isolation.",
    goal: "₦3,200,000",
    raised: "₦1,800,000",
    progress: 56,
    daysLeft: 17,
    image: image,
  },
  {
    id: 13,
    organization: "Tech4Girls",
    title: "Girls in STEM Initiative",
    description:
      "Encouraging girls to pursue science, tech, and engineering through workshops and mentorship.",
    goal: "₦5,500,000",
    raised: "₦3,100,000",
    progress: 56,
    daysLeft: 20,
    image: image,
  },
  {
    id: 14,
    organization: "GreenEarth",
    title: "Recycling Awareness Project",
    description:
      "Educating communities about proper waste management and recycling practices.",
    goal: "₦2,700,000",
    raised: "₦1,200,000",
    progress: 44,
    daysLeft: 23,
    image: image,
  },
  {
    id: 15,
    organization: "Smile Foundation",
    title: "Support for Orphans",
    description:
      "Providing basic needs, education, and emotional support for orphans.",
    goal: "₦5,000,000",
    raised: "₦3,000,000",
    progress: 60,
    daysLeft: 16,
    image: image,
  },
  {
    id: 16,
    organization: "MindWell Africa",
    title: "Mental Health Awareness Drive",
    description:
      "Promoting mental wellness through outreach, counseling, and education programs.",
    goal: "₦4,800,000",
    raised: "₦2,500,000",
    progress: 52,
    daysLeft: 13,
    image: image,
  },
  {
    id: 17,
    organization: "WomenRise",
    title: "Microloans for Women Entrepreneurs",
    description:
      "Empowering women with small business loans to boost self-reliance and income generation.",
    goal: "₦6,000,000",
    raised: "₦4,200,000",
    progress: 70,
    daysLeft: 14,
    image: image,
  },
  {
    id: 18,
    organization: "FutureLeaders",
    title: "Books for Every Child",
    description:
      "Distributing educational materials and books to students in public schools.",
    goal: "₦2,800,000",
    raised: "₦1,600,000",
    progress: 57,
    daysLeft: 9,
    image: image,
  },
  {
    id: 19,
    organization: "SafeSteps",
    title: "Road Safety Education",
    description:
      "Creating awareness about safe road practices to reduce accidents in local communities.",
    goal: "₦1,800,000",
    raised: "₦800,000",
    progress: 44,
    daysLeft: 11,
    image: image,
  },
  {
    id: 20,
    organization: "HeartsUnited",
    title: "Emergency Relief for Flood Victims",
    description:
      "Providing food, shelter, and clothing to families affected by recent floods.",
    goal: "₦7,000,000",
    raised: "₦4,000,000",
    progress: 57,
    daysLeft: 24,
    image: image,
  },
  {
    id: 21,
    organization: "LightHouse Foundation",
    title: "Build a Classroom Project",
    description:
      "Constructing learning spaces in communities with no access to quality school buildings.",
    goal: "₦10,000,000",
    raised: "₦6,000,000",
    progress: 60,
    daysLeft: 20,
    image: image,
  },
  {
    id: 22,
    organization: "CleanAir Africa",
    title: "Reduce Smoke Pollution",
    description:
      "Educating households on cleaner cooking methods to reduce indoor air pollution.",
    goal: "₦2,400,000",
    raised: "₦1,000,000",
    progress: 42,
    daysLeft: 29,
    image: image,
  },
  {
    id: 23,
    organization: "BrightPath Initiative",
    title: "Sponsor a Student Today",
    description:
      "Helping low-income families send their children to school through sponsorships.",
    goal: "₦3,600,000",
    raised: "₦1,500,000",
    progress: 42,
    daysLeft: 21,
    image: image,
  },
  {
    id: 24,
    organization: "HopeRise",
    title: "Hunger Relief Drive",
    description:
      "Delivering essential food packs to internally displaced persons and poor households.",
    goal: "₦5,500,000",
    raised: "₦3,800,000",
    progress: 69,
    daysLeft: 18,
    image: image,
  },
  {
    id: 25,
    organization: "OneVoice Youth",
    title: "Empowering Youth Voters",
    description:
      "Raising civic awareness and participation among young voters through education.",
    goal: "₦1,500,000",
    raised: "₦600,000",
    progress: 40,
    daysLeft: 12,
    image: image,
  },
  {
    id: 26,
    organization: "Bridge2Tomorrow",
    title: "ICT Labs for Secondary Schools",
    description:
      "Equipping schools with computers and internet access to enhance digital literacy.",
    goal: "₦9,000,000",
    raised: "₦5,000,000",
    progress: 55,
    daysLeft: 26,
    image: image,
  },
  {
    id: 27,
    organization: "PureHearts",
    title: "Clean Sanitation Project",
    description:
      "Building toilets and hygiene systems to reduce disease outbreaks in villages.",
    goal: "₦4,200,000",
    raised: "₦2,100,000",
    progress: 50,
    daysLeft: 10,
    image: image,
  },
  {
    id: 28,
    organization: "SafeFuture",
    title: "Protect the Girl Child",
    description:
      "Educating communities on ending child marriage and gender-based violence.",
    goal: "₦6,500,000",
    raised: "₦3,000,000",
    progress: 46,
    daysLeft: 25,
    image: image,
  },
  {
    id: 29,
    organization: "GreenHands",
    title: "Urban Garden Initiative",
    description:
      "Encouraging city dwellers to grow food sustainably through community gardens.",
    goal: "₦2,300,000",
    raised: "₦1,100,000",
    progress: 48,
    daysLeft: 30,
    image: image,
  },
  {
    id: 30,
    organization: "NextGen Dreams",
    title: "Tech Bootcamp for Teens",
    description:
      "Training teenagers in coding, robotics, and innovation to prepare them for the digital future.",
    goal: "₦7,000,000",
    raised: "₦3,500,000",
    progress: 50,
    daysLeft: 14,
    image: image,
  },
];

export default ExploreCards;
